---
title: "Chapter_10"
author: "Taehyun Yoo"
date: '2022-05-24'
output: 
  html_document: 
    keep_md: yes
---

```{r packages, include = FALSE}
#Load packages
library("Rcpp")
library("rstanarm")
library('tidyverse')
library('here')
library("brms")
```

#10.1 Adding predictors to a model
```{r 10.1}
kidiq <- here("..", "KidIQ", "data", "kidiq.csv")
kidiq <- read.csv(kidiq)
kidiq

#starting with a binary predictor
fit1 <- brm(kid_score ~ mom_hs, data=kidiq)
print(fit1)

#a single continuous predictor
fit2 <- brm(kid_score ~ mom_iq, data=kidiq)
print(fit2)

#including both predictors
fit3 <- brm(kid_score ~ mom_hs + mom_iq, data=kidiq)
print(fit3)
```

#10.3 Interactions
```{r 10.3}
fit4 <- brm(kid_score ~ mom_hs + mom_iq + mom_hs:mom_iq, data=kidiq)
print(fit4)
```

#10.4 Indicator variables
```{r 10.4}
earnings <- here("..", "Earnings", "data", "earnings.csv")
earnings <- read.csv(earnings)
earnings

fit_1 <- brm(weight ~ height, data=earnings)
print(fit_1)
coefs_1 <- fixef(fit_1)
predicted_1 <- coefs_1[1,1] + coefs_1[2,1]*66
#new <- data.frame(height=66)
#pred <- posterior_predict(fit_1, newdata=new)
#cat("Predicted weight for a 66-inch-tall person is", round(mean(pred)),
#"pounds with a sd of", round(sd(pred)), "\n")

earnings$c_height <- earnings$height - 66
fit_2 <- brm(weight ~ c_height, data=earnings)
print(fit_2)

fit_3 <- brm(weight ~ c_height + male, data=earnings)
print(fit_3)
coefs_3 <- fixef(fit_3)
predicted <- coefs_3[1,1] + coefs_3[2,1]*4.0 + coefs_3[3,1]*0
#new <- data.frame(c_height=4.0, male=0)
#pred <- posterior_predict(fit_3, newdata=new)
#cat("Predicted weight for a 70-inch-tall woman is", round(mean(pred)),
#"pounds with a sd of", round(sd(pred)), "\n")

fit_4 <- brm(weight ~ c_height + male + factor(ethnicity), data=earnings)
print(fit_4)

earnings$eth <- factor(earnings$ethnicity,
levels=c("White", "Black", "Hispanic", "Other"))
fit_5 <- brm(weight ~ c_height + male + eth, data=earnings)
print(fit_5)

earnings$eth_White <- ifelse(earnings$ethnicity=="White", 1, 0)
earnings$eth_Black <- ifelse(earnings$ethnicity=="Black", 1, 0)
earnings$eth_Hispanic <- ifelse(earnings$ethnicity=="Hispanic", 1, 0)
earnings$eth_Other <- ifelse(earnings$ethnicity=="Other", 1, 0)

fit_6 <- brm(weight ~ height + male + eth_Black + eth_Hispanic +
eth_Other, data=earnings)
```

#10.6 Example: uncertainty in predicting congressional elections
```{r 10.6}
congress <- here("..", "Congress", "data", "congress.csv")
congress <- read.csv(congress)
congress
hist(congress$v88, breaks = 20)

data88 <- data.frame(vote=congress$v88_adj, past_vote=congress$v86_adj,
inc=congress$inc88)
fit88 <- brm(vote ~ past_vote + inc, data=data88)
sims88 <- as.matrix(fit88)
n_sims <- nrow(sims88)

data90 <- data.frame(past_vote=congress$v88_adj, inc=congress$inc90)
pred90 <- posterior_predict(fit88, newdata=data90)
dems_pred <- rep(NA, n_sims)
for (s in 1:n_sims) {
  dems_pred[s] <- sum(pred90[s,] > 0.5)
}
```